# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restbackend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
                ('created_date', models.DateTimeField(verbose_name='date created')),
                ('updated_date', models.DateTimeField(verbose_name='date modified')),
            ],
        ),
    ]
